### ISSUE TITLE
Donkey Kong Land 2 Crashes to Gmenu

### ISSUE THREAD

**Issue by Cralex** [rs90-randomsjunk/gnuboy_rs90#3] opened 2019-05-07 05:28 UTC
I know this isn’t the most accurate emulator, but Donkey Kong Land 2 is decently mainstream so...

Upon starting a new game and entering the world map, gnuboy crashes to Gmenu when pressing A to enter the area: https://www.dropbox.com/s/plg5stjvd3f7ekx/DKL2%20Crash.MOV?dl=0

I have reports in Discord of similar problems with Donkey Kong Land 3, but I don’t have a copy of it with me. Donkey Kong Land 1 seems fine.

**Comment by gameblabla** [comment] 2019-05-07 18:41
It's actually not a crash but a force exit done by the emulator itself. This is what happens in Donkey Kong Land 2 after you try to start a level :
`invalid opcode 0xE3 at address 0x472C, rombank = 2`

The odd thing is this does not happen if you compile gnuboy for x86_64 so i'm not sure what's actually going on. It's possible that the game does try to use an invalid opcode or there's an error somewhere else in the code that causes just that...

**EDIT**: If we disable said die code, then the game will behave very strangely. Unfortunately, it looks like it will need deeper inspection.

**Comment by gameblabla** [comment] 2019-05-07 20:43
https://github.com/rs90-randomsjunk/gnuboy_rs90/commit/cdf29eb998dc3d329ad0ec8bf7d52409c2649274
I've decided to disable killing the emulator if it encounters an invalid opcode. Unfortunately, it's not a true fix and the game will not run properly. (while it does on a PC, strangely enough)

I've also merged some other unrelated code from upstream and that fixed games like Killer Instinct & Extreme Ghostbusters but still enough for DKL2 though.

**Comment by Cralex** [comment] 2019-05-08 03:51
Strangely enough, using the second or third save slot seems to bypass the problem. I am in the process of playing at least up to the first save point to verify that it remains stable. So for posterity: avoid the first save slot!

**Comment by gameblabla** [comment] 2019-05-08 03:53
Turns out this issue with DKL2 was a combination of save corruptions and memory leaks. Using my latest OPK update (i'll make an announcement about it but it fixes DKC), if you remove the corrupted save file and start a new fresh game on slot 1, the first level finally starts. However, input still goes crazy ingame for some reasons.

**EDIT**: Hmm i can't reproduce the input issue anymore. Perhaps it is unrelated.
I'm considering this fixed as of latest commit but i'll still leaving it open before we can confirm that these games are fixed for good.

**Comment by gameblabla** [comment] 2019-05-08 04:33
Had someone else try it on his RS-90 and he told me all of the Donkey Kong Land games, including Donkey Kong land 3 GB & GBC, work fine with no issues or crashing. Guess we can close that issue for good. Do make sure to remove the corrupted save of course.

**Closed as completed by gameblabla** 2019-05-08 04:33 UTC
